---
title: "Course Project for getdata-009"
author: "David Seibel"
date: "November 13, 2014"
output: html_document
---
Course Project for: Johns Hopkins - Getting and Cleaning Data  
instructors: by Jeff Leek, PhD, Roger D. Peng, PhD, Brian Caffo, PhD  
Course Dates: November, 2014  
Student email: seibeldb@gmail.com  

#Project Instructions 
(copied from course materials)

/* bullet  
/** nested bullet  
1. numbered  
1.1. second level  


The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit:  
1. A tidy data set as described below  
2. a link to a Github repository with your script for performing the analysis, and   
3. a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md.   
4. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.   

You should create one R script called run_analysis.R that does the following.  
1. Merges the training and the test sets to create one data set.  
2. Extracts only the measurements on the mean and standard deviation for each measurement.  
3. Uses descriptive activity names to name the activities in the data set  
4. Appropriately labels the data set with descriptive variable names.  
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

Please upload the tidy data set created in step 5 of the instructions. Please upload your data set as a txt file created with write.table() using row.name=FALSE (do not cut and paste a dataset directly into the text box, as this may cause errors saving your submission).

RAW Data Web URL: (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)  
Download date: Wednesday, November 5, 2014 at 3:21 PM (EST)  